name: Test Matrix

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} with Flutter ${{ matrix.flutter-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutter-version: ['3.3.0', '3.10.0', 'stable']
        include:
          # Add beta testing on ubuntu
          - os: ubuntu-latest
            flutter-version: 'beta'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-version == 'stable' || matrix.flutter-version == 'beta' && matrix.flutter-version || 'stable' }}
      
      - name: Flutter doctor
        run: flutter doctor -v
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze
        run: dart analyze --fatal-infos
      
      - name: Run tests
        run: flutter test --coverage --reporter=expanded
      
      - name: Install example dependencies
        working-directory: example
        run: flutter pub get
      
      - name: Test example app
        working-directory: example
        run: flutter test
      
      - name: Build example (Android)
        if: matrix.os == 'ubuntu-latest'
        working-directory: example
        run: flutter build apk --debug
      
      - name: Build example (iOS)
        if: matrix.os == 'macos-latest'
        working-directory: example
        run: flutter build ios --no-codesign --debug
      
      - name: Build example (macOS)
        if: matrix.os == 'macos-latest'
        working-directory: example
        run: flutter build macos --debug
      
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.flutter-version == 'stable'
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info